using System.ComponentModel.DataAnnotations;

namespace ProCoder.Model
{
    public class Achievement
    {
        //Generated by the system
        [Key]
        public int AchieveID { get; set; }
        public string AchieveName { get; set; }
        public string AchieveDes { get; set; }
        public string type { get; set; }
        public int Condition { get; set; }
    }
}
