using System.ComponentModel.DataAnnotations;

namespace ProCoder.Model
{
    public class Comment
    {
        //Generated by the system
        [Key]
        public int CommentID { get; set; }
        public int QuestionID { get; set; }
        public int UserID { get; set; }
        public DateTime CreatedDate { get; set; }

        //Tag
        public string Tags { get; set; }

        //Entered by the user
        public string? CommentText { get; set; }
        [Required]
        public int CommentRating { get; set; }
    }
}

