using System.ComponentModel.DataAnnotations;

namespace ProCoder.Model
{
    public class Solution
    {
        //Generated by the system
        [Key]
        public int SolutionID { get; set; }
        public int UserID { get; set; }
        public int QuestionID { get; set; }

        public string QuestionTitle { get; set; }
        public bool Status { get; set; }
        public DateTime SubmitDate { get; set; }

        //Tag
        public string Tags { get; set; }

        //Entered by the User
        [Required]
        public string SolutionContext { get; set; }
    }
}

