using System.ComponentModel.DataAnnotations;

namespace ProCoder.Model
{
    // The achievements gained by user
    public class UserAchievement
    {
        //Generated by the system
        [Key]
        public int AchievementId { get; set; }
        public int AchieveID { get; set; }
        public int UserID { get; set; }

        public string UserName { get; set; }
        public string AchieveName { get; set; }
        public string AchieveDes { get; set; }
        public string ? AchievementRequirement { get; set; }
        public DateTime AchieveDate { get; set; }
    }
}